displayName=AlchIndicator
author=Wesley Oakley (Aggermor) and Cameron Oakley (Camsterrrr)
description=A plugin that visually indicates if a alchemy spell has been selected.
tags=Alch, Alchemy, Magic, Overlay, QoL
plugins=com.oakleyio.AlchIndicator